
### Ver Posts
GET http://localhost:3000/posts

### Traer los posts
GET http://localhost:3000/api/posts/

### Crear un nuevo post
POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "title": "Nuevo post",
    "description": "Escriba aqui su texto",
    "poster": "http://www.url.com"
}
### Modificar un post realizado
PUT http://localhost:3000/api/posts/1
Content-Type: application/json

{
    "title": 
    "description":
    "poster": 
    
}

### Eliminar un post
DELETE http://localhost:3000/api/posts/1