
### Ver Posts
GET http://localhost:3000/tasks

### Traer los posts
GET http://localhost:3000/api/tasks/

### Crear un nuevo post
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "title": "Nuevo post",
    "description": "Escriba aqui su texto",
    "poster": "http://www.url.com"
}
### Modificar un post realizado
PUT http://localhost:3000/api/tasks/1
Content-Type: application/json

{
    "title": 
    "description":
    "poster": 
    
}

### Eliminar un post
DELETE http://localhost:3000/api/tasks/1